// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: grpc/chitchat.proto

package chitchat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Chat_Connect_FullMethodName     = "/chitchat.chat/Connect"
	Chat_OnGoingChat_FullMethodName = "/chitchat.chat/OnGoingChat"
	Chat_Disconnect_FullMethodName  = "/chitchat.chat/Disconnect"
)

// ChatClient is the client API for Chat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatClient interface {
	Connect(ctx context.Context, in *SimpleMessage, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConnectRespond], error)
	OnGoingChat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SimpleMessage, ChatRespond], error)
	Disconnect(ctx context.Context, in *SimpleMessage, opts ...grpc.CallOption) (*ChatRespond, error)
}

type chatClient struct {
	cc grpc.ClientConnInterface
}

func NewChatClient(cc grpc.ClientConnInterface) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) Connect(ctx context.Context, in *SimpleMessage, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConnectRespond], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Chat_ServiceDesc.Streams[0], Chat_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SimpleMessage, ConnectRespond]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Chat_ConnectClient = grpc.ServerStreamingClient[ConnectRespond]

func (c *chatClient) OnGoingChat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SimpleMessage, ChatRespond], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Chat_ServiceDesc.Streams[1], Chat_OnGoingChat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SimpleMessage, ChatRespond]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Chat_OnGoingChatClient = grpc.BidiStreamingClient[SimpleMessage, ChatRespond]

func (c *chatClient) Disconnect(ctx context.Context, in *SimpleMessage, opts ...grpc.CallOption) (*ChatRespond, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatRespond)
	err := c.cc.Invoke(ctx, Chat_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServer is the server API for Chat service.
// All implementations must embed UnimplementedChatServer
// for forward compatibility.
type ChatServer interface {
	Connect(*SimpleMessage, grpc.ServerStreamingServer[ConnectRespond]) error
	OnGoingChat(grpc.BidiStreamingServer[SimpleMessage, ChatRespond]) error
	Disconnect(context.Context, *SimpleMessage) (*ChatRespond, error)
	mustEmbedUnimplementedChatServer()
}

// UnimplementedChatServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatServer struct{}

func (UnimplementedChatServer) Connect(*SimpleMessage, grpc.ServerStreamingServer[ConnectRespond]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedChatServer) OnGoingChat(grpc.BidiStreamingServer[SimpleMessage, ChatRespond]) error {
	return status.Errorf(codes.Unimplemented, "method OnGoingChat not implemented")
}
func (UnimplementedChatServer) Disconnect(context.Context, *SimpleMessage) (*ChatRespond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedChatServer) mustEmbedUnimplementedChatServer() {}
func (UnimplementedChatServer) testEmbeddedByValue()              {}

// UnsafeChatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServer will
// result in compilation errors.
type UnsafeChatServer interface {
	mustEmbedUnimplementedChatServer()
}

func RegisterChatServer(s grpc.ServiceRegistrar, srv ChatServer) {
	// If the following call pancis, it indicates UnimplementedChatServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Chat_ServiceDesc, srv)
}

func _Chat_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SimpleMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServer).Connect(m, &grpc.GenericServerStream[SimpleMessage, ConnectRespond]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Chat_ConnectServer = grpc.ServerStreamingServer[ConnectRespond]

func _Chat_OnGoingChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServer).OnGoingChat(&grpc.GenericServerStream[SimpleMessage, ChatRespond]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Chat_OnGoingChatServer = grpc.BidiStreamingServer[SimpleMessage, ChatRespond]

func _Chat_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).Disconnect(ctx, req.(*SimpleMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// Chat_ServiceDesc is the grpc.ServiceDesc for Chat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chitchat.chat",
	HandlerType: (*ChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Disconnect",
			Handler:    _Chat_Disconnect_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Chat_Connect_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "OnGoingChat",
			Handler:       _Chat_OnGoingChat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc/chitchat.proto",
}
