// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: chitchat.proto

package chitchat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_chitchat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_chitchat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_chitchat_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type SimpleMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleMessage) Reset() {
	*x = SimpleMessage{}
	mi := &file_chitchat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleMessage) ProtoMessage() {}

func (x *SimpleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chitchat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleMessage.ProtoReflect.Descriptor instead.
func (*SimpleMessage) Descriptor() ([]byte, []int) {
	return file_chitchat_proto_rawDescGZIP(), []int{1}
}

func (x *SimpleMessage) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *SimpleMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Msg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	UnixTime      int64                  `protobuf:"varint,2,opt,name=UnixTime,proto3" json:"UnixTime,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Msg) Reset() {
	*x = Msg{}
	mi := &file_chitchat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_chitchat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_chitchat_proto_rawDescGZIP(), []int{2}
}

func (x *Msg) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Msg) GetUnixTime() int64 {
	if x != nil {
		return x.UnixTime
	}
	return 0
}

func (x *Msg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConnectRespond struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	PrevMessage   []*Msg                 `protobuf:"bytes,2,rep,name=PrevMessage,proto3" json:"PrevMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRespond) Reset() {
	*x = ConnectRespond{}
	mi := &file_chitchat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRespond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRespond) ProtoMessage() {}

func (x *ConnectRespond) ProtoReflect() protoreflect.Message {
	mi := &file_chitchat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRespond.ProtoReflect.Descriptor instead.
func (*ConnectRespond) Descriptor() ([]byte, []int) {
	return file_chitchat_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectRespond) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ConnectRespond) GetPrevMessage() []*Msg {
	if x != nil {
		return x.PrevMessage
	}
	return nil
}

var File_chitchat_proto protoreflect.FileDescriptor

const file_chitchat_proto_rawDesc = "" +
	"\n" +
	"\x0echitchat.proto\x12\bchitchat\"\x1a\n" +
	"\x04User\x12\x12\n" +
	"\x04Uuid\x18\x01 \x01(\tR\x04Uuid\"M\n" +
	"\rSimpleMessage\x12\"\n" +
	"\x04User\x18\x01 \x01(\v2\x0e.chitchat.UserR\x04User\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage\"_\n" +
	"\x03Msg\x12\"\n" +
	"\x04User\x18\x01 \x01(\v2\x0e.chitchat.UserR\x04User\x12\x1a\n" +
	"\bUnixTime\x18\x02 \x01(\x03R\bUnixTime\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\tR\aMessage\"a\n" +
	"\x0eConnectRespond\x12\x1e\n" +
	"\n" +
	"StatusCode\x18\x01 \x01(\x05R\n" +
	"StatusCode\x12/\n" +
	"\vPrevMessage\x18\x02 \x03(\v2\r.chitchat.MsgR\vPrevMessage2\xbf\x01\n" +
	"\x04chat\x12<\n" +
	"\aConnect\x12\x17.chitchat.SimpleMessage\x1a\x18.chitchat.ConnectRespond\x129\n" +
	"\vOnGoingChat\x12\x17.chitchat.SimpleMessage\x1a\r.chitchat.Msg(\x010\x01\x12>\n" +
	"\n" +
	"Disconnect\x12\x17.chitchat.SimpleMessage\x1a\x17.chitchat.SimpleMessageB8Z6https://github.com/Mojjedrengen/ChitChat/grpc/chitchatb\x06proto3"

var (
	file_chitchat_proto_rawDescOnce sync.Once
	file_chitchat_proto_rawDescData []byte
)

func file_chitchat_proto_rawDescGZIP() []byte {
	file_chitchat_proto_rawDescOnce.Do(func() {
		file_chitchat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chitchat_proto_rawDesc), len(file_chitchat_proto_rawDesc)))
	})
	return file_chitchat_proto_rawDescData
}

var file_chitchat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_chitchat_proto_goTypes = []any{
	(*User)(nil),           // 0: chitchat.User
	(*SimpleMessage)(nil),  // 1: chitchat.SimpleMessage
	(*Msg)(nil),            // 2: chitchat.Msg
	(*ConnectRespond)(nil), // 3: chitchat.ConnectRespond
}
var file_chitchat_proto_depIdxs = []int32{
	0, // 0: chitchat.SimpleMessage.User:type_name -> chitchat.User
	0, // 1: chitchat.Msg.User:type_name -> chitchat.User
	2, // 2: chitchat.ConnectRespond.PrevMessage:type_name -> chitchat.Msg
	1, // 3: chitchat.chat.Connect:input_type -> chitchat.SimpleMessage
	1, // 4: chitchat.chat.OnGoingChat:input_type -> chitchat.SimpleMessage
	1, // 5: chitchat.chat.Disconnect:input_type -> chitchat.SimpleMessage
	3, // 6: chitchat.chat.Connect:output_type -> chitchat.ConnectRespond
	2, // 7: chitchat.chat.OnGoingChat:output_type -> chitchat.Msg
	1, // 8: chitchat.chat.Disconnect:output_type -> chitchat.SimpleMessage
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_chitchat_proto_init() }
func file_chitchat_proto_init() {
	if File_chitchat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chitchat_proto_rawDesc), len(file_chitchat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chitchat_proto_goTypes,
		DependencyIndexes: file_chitchat_proto_depIdxs,
		MessageInfos:      file_chitchat_proto_msgTypes,
	}.Build()
	File_chitchat_proto = out.File
	file_chitchat_proto_goTypes = nil
	file_chitchat_proto_depIdxs = nil
}
